[package]
name = "rust-device-detector"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
indexmap = { version = "2.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
hyper = { version = "0.14", features = ["server", "tcp", "http1", "http2"] }
serde_yaml = "0.9"
serde_json = "1.0"
fancy-regex = "0.11"
anyhow = "1.0"
itertools = "0.11"
lazy_static = "1.4"
once_cell = "1.8"
tokio = { version = "1", features = ["full"] }
version-compare = "0.1.1"
fallible-iterator = "0.3"
moka = { version = "0.11", features = ["future"], optional = true }


[dev-dependencies]
futures = "0.3"
stats_alloc = "0.1.1"
glob = "0.3"

[features]
default = []
full = ["cache"]
# cache is a feature because moka brings in a lot of dependencies.
cache = ["dep:moka"]

# these tests take a long time without optimization
[profile.test]
opt-level = 3
